export const lightTheme = {
  background: "bg-gray-50",
  text: "text-gray-900",
  textSecondary: "text-gray-600",
  textMuted: "text-gray-500",
  card: "bg-white",
  cardHover: "hover:bg-gray-50",
  border: "border-gray-200",
  buttonPrimary: "bg-indigo-600 hover:bg-indigo-700 text-white",
  buttonSecondary: "bg-gray-100 hover:bg-gray-200 text-gray-900",
  input: "bg-white border-gray-300 focus:border-indigo-500",
  navbar: "bg-white",
  navbarText: "text-gray-900",
  navbarHover: "hover:bg-gray-100",
  shadow: "shadow-sm",
};

export const darkTheme = {
  background: "bg-gray-900",
  text: "text-white",
  textSecondary: "text-gray-300",
  textMuted: "text-gray-400",
  card: "bg-gray-800",
  cardHover: "hover:bg-gray-700",
  border: "border-gray-700",
  buttonPrimary: "bg-indigo-600 hover:bg-indigo-500 text-white",
  buttonSecondary: "bg-gray-700 hover:bg-gray-600 text-white",
  input: "bg-gray-800 border-gray-700 focus:border-indigo-500",
  navbar: "bg-gray-900",
  navbarText: "text-white",
  navbarHover: "hover:bg-gray-800",
  shadow: "shadow-md shadow-gray-900/10",
}; 